In [2]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
import pickle

In [3]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10002 non-null  int64
 1   CustomerId       10002 non-null  int64
 2   Surname          10002 non-null  str
 3   CreditScore      10002 non-null  int64
 4   Geography        10001 non-null  str
 5   Gender           10002 non-null  str
 6   Age              10001 non-null  float64
 7   Tenure           10002 non-null  int64
 8   Balance          10002 non-null  float64
 9   NumOfProducts    10002 non-null  int64
 10  HasCrCard        10001 non-null  float64
 11  IsActiveMember   10001 non-null  float64
 12  EstimatedSalary  10002 non-null  float64
 13  Exited           10002 non-null  int64
dtypes: float64(5), int64(6), str(3)
memory usage: 1.2 MB

In [5]:
#Precprocessing 

""" 1. Remove irrelevant features
2. Converting Gender column to numerical using Label Encoding 
3. Removing the null values 
4. Converting geography column data to one-Hot-Encoder  
5. Scaling all the values
"""

' 1. Remove irrelevant features\n2. Converting Gender column to numerical using Label Encoding \n3. Removing the null values \n4. Converting geography column data to one-Hot-Encoder  \n5. Scaling all the values\n'

In [6]:
# Removing irrelevant features
data = data.drop(['RowNumber', 'CustomerId', 'Surname'],axis = 1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [ ]:
# converting gender col. data into numbers using label Encoder 
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,0,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,0,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [8]:
# To fill null values
data['Geography'].unique()

<ArrowStringArray>
['France', 'Spain', nan, 'Germany']
Length: 4, dtype: str

In [9]:
# Fill null values of Geography Column
data['Geography'].value_counts()
data['Geography'] = data['Geography'].fillna('France')

In [10]:
data['Age'] = data['Age'].fillna(data['Age'].mean())
data['Age']

0        42.0
1        41.0
2        42.0
3        39.0
4        43.0
         ...
9997     36.0
9998     42.0
9999     42.0
10000    28.0
10001    28.0
Name: Age, Length: 10002, dtype: float64

In [11]:
# Fill the null values of IsActiveMember column
data['IsActiveMember'].value_counts()
data['IsActiveMember']=data['IsActiveMember'].fillna(1.0)

In [12]:
# Fill the null values of HasCrCard column
data['HasCrCard'].value_counts()
data['HasCrCard'] = data['HasCrCard'].fillna(1.0)

In [13]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10002 non-null  int64
 1   Geography        10002 non-null  str
 2   Gender           10002 non-null  int64
 3   Age              10002 non-null  float64
 4   Tenure           10002 non-null  int64
 5   Balance          10002 non-null  float64
 6   NumOfProducts    10002 non-null  int64
 7   HasCrCard        10002 non-null  float64
 8   IsActiveMember   10002 non-null  float64
 9   EstimatedSalary  10002 non-null  float64
 10  Exited           10002 non-null  int64
dtypes: float64(5), int64(5), str(1)
memory usage: 918.3 KB

In [14]:
# convert geography column into one-hot-encoding 
from sklearn.preprocessing import OneHotEncoder 

onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10002 stored elements and shape (10002, 3)>

In [15]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], shape=(10002, 3))

In [16]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [17]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,0,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,0,43.0,2,125510.82,1,1.0,1.0,79084.10,0

In [18]:
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoder_df

       Geography_France  Geography_Germany  Geography_Spain
0                   1.0                0.0              0.0
1                   0.0                0.0              1.0
2                   1.0                0.0              0.0
3                   1.0                0.0              0.0
4                   0.0                0.0              1.0
...                 ...                ...              ...
9997                1.0                0.0              0.0
9998                0.0                1.0              0.0
9999                0.0                1.0              0.0
10000               1.0                0.0              0.0
10001               1.0                0.0              0.0

[10002 rows x 3 columns]

In [22]:
# combine one hot encoder columns with the original dataframe and remove the existing geography column
data = pd.concat([data.drop('Geography', axis =1), geo_encoder_df], axis = 1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42.0,2,0.00,1,1.0,1.0,101348.88,1,1.0,0.0,0.0
1,608,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0,0.0,0.0,1.0
2,502,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1,1.0,0.0,0.0
3,699,0,39.0,1,0.00,2,0.0,0.0,93826.63,0,1.0,0.0,0.0
4,850,0,43.0,2,125510.82,1,1.0,1.0,79084.10,0,0.0,0.0,1.0

In [23]:
# Save the label_encoder and one hot encoder technique here
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [24]:
# Divide the dataset in to training and testing data
X = data.drop('Exited', axis =1)
y=data['Exited']

# split the data into trainin and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#SCaling the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

X_train

array([[-0.19344335,  0.91360328,  0.29613055, ..., -0.99737876,
         1.72529422, -0.57710974],
       [-0.95045188,  0.91360328, -1.42278638, ..., -0.99737876,
        -0.57961128,  1.73277271],
       [ 0.10728607, -1.094567  , -0.84981407, ...,  1.00262813,
        -0.57961128, -0.57710974],
       ...,
       [ 0.87466458, -1.094567  , -0.08585099, ...,  1.00262813,
        -0.57961128, -0.57710974],
       [ 0.16950595,  0.91360328,  0.39162594, ...,  1.00262813,
        -0.57961128, -0.57710974],
       [ 0.48060534,  0.91360328,  1.15558902, ..., -0.99737876,
         1.72529422, -0.57710974]], shape=(8001, 12))

In [25]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [26]:
### ANN IMPLEMENTATION

In [38]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [28]:
# Build  our ANN model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # 1st hidden layer
    Dense(32, activation='relu'),  # 2nd hidden layer
    Dense(1, activation='sigmoid') #output layer
    
])

c:\Users\JEET\Desktop\QGen AI\DL code work\.dl\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [29]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
# compile the model
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [31]:
# set up the tensorboard (visualization)
log_dir = "logs/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir = log_dir, histogram_freq=1)
tensorflow_callback

In [32]:
# set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience = 5, restore_best_weights=True)
early_stopping_callback

In [33]:
# Train the model
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs = 100, callbacks=
                      [early_stopping_callback, tensorflow_callback])

Epoch 1/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8091 - loss: 0.4533 - val_accuracy: 0.8316 - val_loss: 0.4055
Epoch 2/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8403 - loss: 0.3852 - val_accuracy: 0.8556 - val_loss: 0.3616
Epoch 3/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8528 - loss: 0.3540 - val_accuracy: 0.8616 - val_loss: 0.3490
Epoch 4/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8546 - loss: 0.3430 - val_accuracy: 0.8611 - val_loss: 0.3467
Epoch 5/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8584 - loss: 0.3389 - val_accuracy: 0.8621 - val_loss: 0.3474
Epoch 6/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8606 - loss: 0.3378 - val_accuracy: 0.8641 - val_loss: 0.3442
Epoch 7/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8654 - loss: 0.3319 - val_accuracy: 0.8586 - val_loss: 0.3491
Epoch 8/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8631 - loss: 0.3311 - val_accuracy: 0.8616 - val_loss: 0.3465
Epoch 9/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8624 - loss: 0.3294 - val_accuracy: 0.8656 - val_loss: 0.3436
Epoch 10/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8638 - loss: 0.3278 - val_accuracy: 0.8611 - val_loss: 0.3463
Epoch 11/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8653 - loss: 0.3245 - val_accuracy: 0.8621 - val_loss: 0.3457
Epoch 12/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8658 - loss: 0.3225 - val_accuracy: 0.8621 - val_loss: 0.3450
Epoch 13/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8666 - loss: 0.3206 - val_accuracy: 0.8636 - val_loss: 0.3429
Epoch 14/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8671 - loss: 0.3200 - val_accuracy: 0.8626 - val_loss: 0.3436
Epoch 15/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8685 - loss: 0.3191 - val_accuracy: 0.8591 - val_loss: 0.3460
Epoch 16/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8671 - loss: 0.3157 - val_accuracy: 0.8606 - val_loss: 0.3443
Epoch 17/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8681 - loss: 0.3146 - val_accuracy: 0.8596 - val_loss: 0.3447
Epoch 18/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8671 - loss: 0.3141 - val_accuracy: 0.8626 - val_loss: 0.3462

In [34]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [39]:
# to do the vizualization we have to load the Tensorboard Extention
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [40]:
# reloading when tensorboard vizualization is not visible
%reload_ext tensorboard
# !taskkill /PID 28460  /F

In [41]:
%tensorboard --logdir logs/fit/ --port 6010

Reusing TensorBoard on port 6010 (pid 1436), started 0:18:57 ago. (Use '!kill 1436' to kill it.)