In [13]:
import tensorflow as tf
from tensorflow.keras.models import load_model  #type:ignore
import pickle
import pandas as pd

In [3]:
# load the trained model, scaler, one-hot-encoding, label-encoder
model=load_model('model.h5')

with open('onehot_encoder_geo.pkl', 'rb') as file:
    label_encoder_geo=pickle.load(file)
    
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender=pickle.load(file)
    
with open('scaler.pkl', 'rb')as file:
    scaler=pickle.load(file)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [4]:
# Example input data
input_data={
    'CreditScore':50000,
    'Geography':'France',
    'Gender':'Female',
    'Age':30,
    'Tenure':4,
    'Balance':60000,
    'NumOfProducts':3,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

input_data

{'CreditScore': 50000,
 'Geography': 'France',
 'Gender': 'Female',
 'Age': 30,
 'Tenure': 4,
 'Balance': 60000,
 'NumOfProducts': 3,
 'HasCrCard': 1,
 'IsActiveMember': 1,
 'EstimatedSalary': 50000}

In [5]:
# One-hot encoding for 'Geography'
geo_encoded=label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\JEET\Desktop\QGen AI\DL code work\.dl\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [6]:
# Here input data is in the key_value format, so we have to convert it into dataframe 
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,50000,France,Female,30,4,60000,3,1,1,50000

In [7]:
# Encode categorical variable (Gender column)
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,50000,France,0,30,4,60000,3,1,1,50000

In [8]:
# Concatination of one hot encoded and drop the existing geography column
input_df=pd.concat([input_df.drop("Geography", axis=1), geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,50000,0,30,4,60000,3,1,1,50000,1.0,0.0,0.0

In [9]:
# Scaling the input data
input_scaled=scaler.transform(input_df)
input_scaled

array([[ 5.05900058e+02, -1.10158775e+00, -8.55101667e-01,
        -3.84185059e-01, -2.77345589e-01,  2.45913540e+00,
         6.49749829e-01,  9.74829420e-01, -8.37406840e-01,
         9.75804859e-01, -5.75619080e-01, -5.60226950e-01]])

In [10]:
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step

array([[0.]], dtype=float32)

In [11]:
# probability of the prediction
prediction_prob=prediction[0][0]
prediction_prob

np.float32(0.0)

In [ ]:
if prediction_prob>0.5:
    print("The customer is likely to churn")
else:
    print("The customer is not likely to churn")

The customer is not likely to churn